/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */



package com.mycompany.bulldogsticketingsystem;
import javax.swing.UIManager;
/**
 *
 * @author Kaede
 */
public class StudentDashboard extends javax.swing.JFrame {

    /**
     * Creates new form StudentDashboard
     */
    public StudentDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        ExitX = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        WelcomeUser = new javax.swing.JLabel();
        SubmitATicket = new javax.swing.JLabel();
        FirstName = new javax.swing.JLabel();
        MiddleName = new javax.swing.JLabel();
        LastName = new javax.swing.JLabel();
        StudentNumber = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        TypeOfDocument = new javax.swing.JLabel();
        NumberOfCopies = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        SpecialInstruction = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PaymentType = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        POP_BTN = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        TOTALPAID_JTXF = new javax.swing.JTextField();
        FNAME_JTXF = new javax.swing.JTextField();
        COPIES_JTXF = new javax.swing.JTextField();
        MNAME_JTXF = new javax.swing.JTextField();
        LNAME_JTXF = new javax.swing.JTextField();
        STUDNO_JTXF = new javax.swing.JTextField();
        EMAIL_JTXF = new javax.swing.JTextField();
        SPECINS_JTXF = new javax.swing.JTextField();
        DOCTYPE_JTXF = new javax.swing.JComboBox<>();
        PURPOSE_JTXF = new javax.swing.JComboBox<>();
        PAYMETH_JTXF = new javax.swing.JComboBox<>();
        SecondBgStudentDashboard = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(50, 62, 143));
        jPanel5.setForeground(new java.awt.Color(50, 62, 143));
        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 810, 970, 10));

        jPanel3.setBackground(new java.awt.Color(50, 62, 143));
        jPanel3.setForeground(new java.awt.Color(50, 62, 143));
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 40, 10, 780));

        jPanel4.setBackground(new java.awt.Color(50, 62, 143));
        jPanel4.setForeground(new java.awt.Color(50, 62, 143));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ExitX.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ExitX.setForeground(new java.awt.Color(255, 255, 255));
        ExitX.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ExitX.setText("    X");
        ExitX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitXMouseClicked(evt);
            }
        });
        jPanel4.add(ExitX, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, 50, 30));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 40));

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel1.setBackground(new java.awt.Color(50, 62, 143));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PaymentDetails.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 540));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 380, 540));

        WelcomeUser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        WelcomeUser.setForeground(new java.awt.Color(12, 40, 105));
        WelcomeUser.setText("Welcome, (User)");
        jPanel1.add(WelcomeUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 50, 200, 50));

        SubmitATicket.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        SubmitATicket.setForeground(new java.awt.Color(12, 40, 105));
        SubmitATicket.setText("Submit a Ticket");
        jPanel1.add(SubmitATicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 170, 20));

        FirstName.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        FirstName.setForeground(new java.awt.Color(12, 40, 105));
        FirstName.setText("First Name:");
        jPanel1.add(FirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 90, 20));

        MiddleName.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        MiddleName.setForeground(new java.awt.Color(12, 40, 105));
        MiddleName.setText("Middle Name:");
        MiddleName.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(MiddleName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 120, 20));

        LastName.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        LastName.setForeground(new java.awt.Color(12, 40, 105));
        LastName.setText("Last Name:");
        jPanel1.add(LastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 110, 20));

        StudentNumber.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        StudentNumber.setForeground(new java.awt.Color(12, 40, 105));
        StudentNumber.setText("Student No:");
        jPanel1.add(StudentNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 130, 20));

        Email.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Email.setForeground(new java.awt.Color(12, 40, 105));
        Email.setText("Email:");
        jPanel1.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 120, 20));

        TypeOfDocument.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        TypeOfDocument.setForeground(new java.awt.Color(12, 40, 105));
        TypeOfDocument.setText("Type of Document:");
        jPanel1.add(TypeOfDocument, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 140, 20));

        NumberOfCopies.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        NumberOfCopies.setForeground(new java.awt.Color(12, 40, 105));
        NumberOfCopies.setText("No. of Copies:");
        jPanel1.add(NumberOfCopies, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 130, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(12, 40, 105));
        jLabel4.setText("Purpose:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 110, -1));

        SpecialInstruction.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        SpecialInstruction.setForeground(new java.awt.Color(12, 40, 105));
        SpecialInstruction.setText("Special Instruction:");
        jPanel1.add(SpecialInstruction, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, 150, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(12, 40, 105));
        jLabel6.setText("For CTC of Grade and CoR, please specify here the AY and term.");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 540, -1, -1));

        jLabel5.setForeground(new java.awt.Color(12, 40, 105));
        jLabel5.setText("(Ex. CTC  of Grades - AY 2022-2023 1st, CoR - AY 2023-2024 2nd) ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 560, -1, -1));

        PaymentType.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        PaymentType.setForeground(new java.awt.Color(12, 40, 105));
        PaymentType.setText("Payment Method:");
        jPanel1.add(PaymentType, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 690, 130, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(12, 40, 105));
        jLabel3.setText("Proof of Payment:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 760, 130, 20));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(12, 40, 105));
        jLabel1.setText("Total Amount Paid:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 720, 150, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(12, 40, 105));
        jLabel7.setText("Required Document:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 800, -1, -1));

        jButton1.setText("Attach a file");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 800, 220, -1));

        POP_BTN.setText("Attach a File");
        jPanel1.add(POP_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 760, 220, -1));

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(153, 0, 0));
        jButton4.setText("Cancel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 870, 140, 50));

        jButton2.setBackground(new java.awt.Color(50, 62, 143));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(12, 40, 105));
        jButton2.setText("Submit Ticket");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 870, 140, 50));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(50, 62, 143));
        jButton3.setText("View Submitted Ticket");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 870, 220, 50));

        TOTALPAID_JTXF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TOTALPAID_JTXFActionPerformed(evt);
            }
        });
        jPanel1.add(TOTALPAID_JTXF, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 720, 220, 30));

        FNAME_JTXF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FNAME_JTXFActionPerformed(evt);
            }
        });
        jPanel1.add(FNAME_JTXF, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 220, 30));

        COPIES_JTXF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COPIES_JTXFActionPerformed(evt);
            }
        });
        jPanel1.add(COPIES_JTXF, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 220, 30));
        jPanel1.add(MNAME_JTXF, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 220, 30));
        jPanel1.add(LNAME_JTXF, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 220, 30));
        jPanel1.add(STUDNO_JTXF, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 220, 30));

        EMAIL_JTXF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EMAIL_JTXFActionPerformed(evt);
            }
        });
        jPanel1.add(EMAIL_JTXF, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 220, 30));

        SPECINS_JTXF.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        SPECINS_JTXF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SPECINS_JTXFActionPerformed(evt);
            }
        });
        jPanel1.add(SPECINS_JTXF, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 580, 360, 100));

        DOCTYPE_JTXF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select your type of document", "Assigned Flowchart/Curriculum", "Certificate of Attendance", "Certificate of Course Description", "Certificate of English Medium", "Certificate of Enrollment", "Certificate of GWA", "Certificate of Registration", "CTC of Grades", "Honorable Dismissal/Transfer Credentials", "Student Flowchart", "Transcript of Records" }));
        DOCTYPE_JTXF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOCTYPE_JTXFActionPerformed(evt);
            }
        });
        jPanel1.add(DOCTYPE_JTXF, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 220, -1));

        PURPOSE_JTXF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select your Purpose", "Employment", "Scholarship/Educational Assistance", "Other" }));
        PURPOSE_JTXF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PURPOSE_JTXFActionPerformed(evt);
            }
        });
        jPanel1.add(PURPOSE_JTXF, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, 220, -1));

        PAYMETH_JTXF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Payment Method", "Gcash", "Bank Transfer" }));
        jPanel1.add(PAYMETH_JTXF, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 690, 220, -1));

        SecondBgStudentDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BgStudentDashboard.png"))); // NOI18N
        jPanel1.add(SecondBgStudentDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 930, 950));

        jScrollPane2.setViewportView(jPanel1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 30, 990, 790));

        setSize(new java.awt.Dimension(969, 821));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitXMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitXMouseClicked

    private void COPIES_JTXFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COPIES_JTXFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_COPIES_JTXFActionPerformed

    private void FNAME_JTXFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FNAME_JTXFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FNAME_JTXFActionPerformed

    private void DOCTYPE_JTXFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOCTYPE_JTXFActionPerformed
        
        
    }//GEN-LAST:event_DOCTYPE_JTXFActionPerformed

    private void EMAIL_JTXFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EMAIL_JTXFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EMAIL_JTXFActionPerformed

    private void SPECINS_JTXFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SPECINS_JTXFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SPECINS_JTXFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PURPOSE_JTXFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PURPOSE_JTXFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PURPOSE_JTXFActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void TOTALPAID_JTXFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TOTALPAID_JTXFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TOTALPAID_JTXFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField COPIES_JTXF;
    private javax.swing.JComboBox<String> DOCTYPE_JTXF;
    private javax.swing.JTextField EMAIL_JTXF;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel ExitX;
    private javax.swing.JTextField FNAME_JTXF;
    private javax.swing.JLabel FirstName;
    private javax.swing.JTextField LNAME_JTXF;
    private javax.swing.JLabel LastName;
    private javax.swing.JTextField MNAME_JTXF;
    private javax.swing.JLabel MiddleName;
    private javax.swing.JLabel NumberOfCopies;
    private javax.swing.JComboBox<String> PAYMETH_JTXF;
    private javax.swing.JButton POP_BTN;
    private javax.swing.JComboBox<String> PURPOSE_JTXF;
    private javax.swing.JLabel PaymentType;
    private javax.swing.JTextField SPECINS_JTXF;
    private javax.swing.JTextField STUDNO_JTXF;
    private javax.swing.JLabel SecondBgStudentDashboard;
    private javax.swing.JLabel SpecialInstruction;
    private javax.swing.JLabel StudentNumber;
    private javax.swing.JLabel SubmitATicket;
    private javax.swing.JTextField TOTALPAID_JTXF;
    private javax.swing.JLabel TypeOfDocument;
    private javax.swing.JLabel WelcomeUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
